# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
      include: scope
    groups:
      api-pip-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/canary"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
      include: scope
    groups:
      canary-pip-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
      include: scope
    groups:
      cargo-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - "*"
