version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
    commands:
      - cd canary
      - make setup
  build:
    commands:
      - echo Build started on `date`
      - sam build --parallel --cached
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --s3-bucket ${S3_BUCKET} --s3-prefix canary --kms-key-id ${CODEBUILD_KMS_KEY_ID} --no-progressbar --signing-profiles rDependencyLayer=${SIGNING_PROFILE} rCanaryVpcFunction=${SIGNING_PROFILE} rCanaryNoVpcFunction=${SIGNING_PROFILE} --output-template-file packaged.yml

artifacts:
  base-directory: canary
  files:
    - packaged.yml  # Used by Deploy:DeployCanary
    - template_configuration.json  # Used by Deploy:DeployCanary
  discard-paths: yes

cache:
  files:
    - '/root/.cache/**/*'
    - '/root/canary/.aws-sam/**/*'
    - '/root/canary/.venv/**/*'
