[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
(
  /(
      \.venv
    | \.aws-sam
    | \.github
    | \.vscode
    | \.cargo
    | \.idea
    | \target
    | \scripts
    | \docs
    | \site
  )/
)
'''
