version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd parent
      - make build-docker

  post_build:
    commands:
      - echo Build completed on `date`
      - CONTAINER_ID=$(docker create parent-vault:latest)
      - docker cp $CONTAINER_ID:/app/parent-vault ./parent-vault
      - docker rm $CONTAINER_ID

artifacts:
  discard-paths: yes
  files:
    - parent/parent-vault  # Used by Deploy:DeployVault

cache:
  files:
    - '/root/.cargo/registry/**/*'
    - '/root/.docker/**/*'
